"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
load_dotenv()

from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-y_2fk#jetyjb^wlwc-@=#av$xrfde2lmc3^3f4#%ki6$fh@r6p')

# DEBUG solo se activa explícitamente en desarrollo. Railway y Render quedan
# en modo producción aunque no definan una variable específica de plataforma.
DEBUG = os.environ.get('DEBUG', '').lower() == 'true'

ALLOWED_HOSTS = ['ample-vision-production-c2b3.up.railway.app']
for hostname in (
    os.environ.get('RENDER_EXTERNAL_HOSTNAME'),
    os.environ.get('RAILWAY_PUBLIC_DOMAIN'),
):
    if hostname:
        ALLOWED_HOSTS.append(hostname)
for hostname in os.environ.get('ALLOWED_HOSTS', '').split(','):
    hostname = hostname.strip()
    if hostname:
        ALLOWED_HOSTS.append(hostname)
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

TIME_ZONE = 'America/La_Paz'
USE_TZ = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'config',
    'rest_framework',
    'corsheaders',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Agregado para static files en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# CORS settings
# CORS settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # tu frontend local
    "https://asorbolsczt.vercel.app",  # producción
    "https://inscripcion-asorbo.vercel.app"
]
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_NAME = "csrftoken"        # nombre de la cookie
CSRF_COOKIE_HTTPONLY = False  # para que pueda ser accedido desde JavaScript


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de base de datos para desarrollo y producción
#DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.sqlite3',
#       'NAME': BASE_DIR / 'db.sqlite3',
#   }
#}

# =========================
# DATABASE CONFIGURATION
# =========================

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",  # fallback para desarrollo
        conn_max_age=600,
        conn_health_checks=True,
    )
}
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'asorbol_produccion',
#        'USER': 'asorbol_produccion_user',
#        'PASSWORD': 'rjYAGxU0raFwAxQSdO2jpXIPVXeVlgMQ',
#        'HOST': 'dpg-d5n3vrkmrvns73fh6oog-a.oregon-postgres.render.com',
#        'PORT': '5432',
#    }
#}




# Si hay DATABASE_URL (en producción), usar PostgreSQL
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-bo'

# Las fechas de inscripción y sus gráficas corresponden al horario del evento.
TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# ✅ Configuraciones CRUCIALES para Render
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Donde se recopilarán los archivos estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Security settings for production
if not DEBUG:
    # Security settings
    # Railway termina HTTPS en su proxy y comunica el protocolo original
    # mediante este encabezado. Sin esta opción Django entra en un bucle 301.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
