# Generated by Django 5.2.5 on 2026-01-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('pagoTelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pagoFecha', models.DateField(blank=True, null=True)),
                ('pagoHora', models.TimeField(blank=True, null=True)),
                ('pagoComprobante', models.CharField(blank=True, max_length=200, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.iglesia')),
            ],
        ),
    ]
