# Generated by Django 5.2.5 on 2026-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
