# Generated by Django 5.2.5 on 2026-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_inscrito_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='pagoComprobante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
