# Generated by Django 5.2.5 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_inscrito_pagocomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='primer_retiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='motivo_retiro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
